### ISSUE TITLE
Feature: support full configuration at run-time

### ISSUE THREAD

**Issue by fireproofsocks** [BinaryNoggin/bamboo_config_adapter#3]
I can currently do something like this:
```
# in my config
config :my_app,
       MyApp.Mailer,
       adapter: Bamboo.ConfigAdapter,
       chained_adapter: Bamboo.MailgunAdapter
```

And then I can do something like
```
new_email(to: "target@mail.com", ...)
|> Bamboo.ConfigAdapter.Email.put_config(%{
        api_key: "xxxxxxx",
        domain: "yyyyyyy.mailgun.org"})
|> Mailer.deliver_now()
```

it would be nice if it were possible to supply the `chained_adapter` at runtime so I can send emails via any ESP.

**Comment by adkron** [comment]
I don't know when I will have time to dig into this. I want to get it done if you have time for a PR that would be helpful.

**Comment by fireproofsocks** [comment]
I'm eyeballing a PR for phase2 of my project. If we get around to it, we can refer to this issue. Thanks!

**Comment by adkron** [comment]
Please update to 1.0.0 for chained adapters to be configured at compile time or runtime.
